export const SELECT_USER = 'SELECT_USER'
export const SET_USERS = 'SET_USERS'
export const SELECT_DATE_PERIOD = 'SELECT_DATE_PERIOD'




// export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN'
// export const SET_REDIRECT = 'SET_REDIRECT'
// export const SET_TIME_REPORT = 'SET_TIME_REPORT'
// export const SET_DATETIME_PERIOD = 'SET_DATETIME_PERIOD'
// export const TOGGLE_SHOW_NEW_ROW = 'TOGGLE_SHOW_NEW_ROW'
// export const SET_SLACK_USER = 'SET_SLACK_USER'